import * as fs from 'fs';
import * as path from 'path';

interface DashboardConfig {
	projectName?: string;
	brandName?: string;
	pageTitle?: string;
	historyIndexPath?: string;
	emptyTitle?: string;
	emptyMessage?: string;
	errorTitle?: string;
	errorMessage?: string;
	historyDir?: string;
}

// Defaults — used when the consumer hasn't overridden a value
const DEFAULTS: Required<DashboardConfig> = {
	projectName: '',
	brandName: 'pw_dashboard',
	pageTitle: 'Test History Dashboard',
	historyIndexPath: 'history-index.json',
	emptyTitle: 'No test history yet',
	emptyMessage: 'Run your tests to start tracking history.',
	errorTitle: 'Could not load history',
	errorMessage: 'Make sure history-index.json is in the same directory.',
	historyDir: 'tests/report/test-history',
};

function loadConsumerConfig(): DashboardConfig {
	const configPath = path.resolve(process.cwd(), 'pw-dashboard.config.js');
	if (fs.existsSync(configPath)) {
		try {
			const cfg = require(configPath) as DashboardConfig;
			console.log(
				`\nFound pw-dashboard.config.js — applying your settings.`,
			);
			return cfg;
		} catch (err) {
			console.warn(
				`\nWarning: could not read pw-dashboard.config.js — using defaults.\n${String(err)}`,
			);
		}
	}
	return {};
}

function injectConfig(html: string, cfg: Required<DashboardConfig>): string {
	const configBlock = `const CONFIG = {
  pageTitle:        ${JSON.stringify(cfg.pageTitle)},
  projectName:      ${JSON.stringify(cfg.projectName)},
  brandName:        ${JSON.stringify(cfg.brandName)},
  historyIndexPath: ${JSON.stringify(cfg.historyIndexPath)},
  emptyTitle:       ${JSON.stringify(cfg.emptyTitle)},
  emptyMessage:     ${JSON.stringify(cfg.emptyMessage)},
  errorTitle:       ${JSON.stringify(cfg.errorTitle)},
  errorMessage:     ${JSON.stringify(cfg.errorMessage)},
};`;

	// Replace the entire CONFIG block between the banner comments
	return html.replace(
		/\/\/ ─+\n\/\/ CONFIG[\s\S]*?\/\/ ─+/,
		`// ─────────────────────────────────────────────────────────────────────────────\n// CONFIG — generated by pw-history-init · edit pw-dashboard.config.js to change\n// ─────────────────────────────────────────────────────────────────────────────\n${configBlock}\n// ─────────────────────────────────────────────────────────────────────────────`,
	);
}

function main() {
	const consumerCfg = loadConsumerConfig();
	const cfg: Required<DashboardConfig> = { ...DEFAULTS, ...consumerCfg };

	const src = path.resolve(__dirname, '../dashboard/index.html');
	const destDir = path.resolve(process.cwd(), cfg.historyDir);
	const dest = path.join(destDir, 'index.html');

	if (!fs.existsSync(destDir)) {
		fs.mkdirSync(destDir, { recursive: true });
	}

	const template = fs.readFileSync(src, 'utf-8');
	const output = injectConfig(template, cfg);

	fs.writeFileSync(dest, output, 'utf-8');

	console.log(`\n✓ Dashboard written to:\n  ${dest}\n`);
	if (!consumerCfg.projectName) {
		console.log(
			`Tip: create pw-dashboard.config.js in your project root to set your project name:\n`,
		);
		console.log(`  module.exports = {`);
		console.log(`    projectName: 'Your Project Name',`);
		console.log(`  };\n`);
	}
	console.log(`Serve with: npx serve ${cfg.historyDir}\n`);
}

main();
