#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

interface DashboardConfig {
	projectName?: string;
	brandName?: string;
	pageTitle?: string;
	historyIndexPath?: string;
	emptyTitle?: string;
	emptyMessage?: string;
	errorTitle?: string;
	errorMessage?: string;
	historyDir?: string;
}

// Defaults — used when the consumer hasn't overridden a value
const DEFAULTS: Required<DashboardConfig> = {
	projectName: '',
	brandName: 'pw_dashboard',
	pageTitle: 'Test History Dashboard',
	historyIndexPath: 'history-index.json',
	emptyTitle: 'No test history yet',
	emptyMessage: 'Run your tests to start tracking history.',
	errorTitle: 'Could not load history',
	errorMessage: 'Make sure history-index.json is in the same directory.',
	historyDir: 'tests/report/test-history',
};

const CONFIG_CANDIDATES = [
	'pw-dashboard.config.js',
	'pw-dashboard.config.cjs',
	'pw-dashboard.config.mjs',
	'pw_dashboard.config.js',
	'pw_dashboard.config.cjs',
	'pw_dashboard.config.mjs',
	'pw-dashboard.config.ts',
	'pw_dashboard.config.ts',
];

function normalizeConfig(raw: unknown): DashboardConfig {
	if (raw && typeof raw === 'object') {
		const maybeModule = raw as { default?: unknown };
		if (maybeModule.default && typeof maybeModule.default === 'object') {
			return maybeModule.default as DashboardConfig;
		}
		return raw as DashboardConfig;
	}
	return {};
}

async function importEsmModule(modulePath: string): Promise<unknown> {
	// Keep native dynamic import available when this file is compiled to CommonJS.
	const dynamicImport = new Function('p', 'return import(p)');
	return dynamicImport(modulePath);
}

async function loadConfigFile(configPath: string): Promise<DashboardConfig> {
	try {
		delete require.cache[require.resolve(configPath)];
		const cfg = require(configPath);
		return normalizeConfig(cfg);
	} catch (err) {
		const code = (err as NodeJS.ErrnoException)?.code;
		if (code !== 'ERR_REQUIRE_ESM') {
			throw err;
		}

		const imported = await importEsmModule(pathToFileURL(configPath).href);
		return normalizeConfig(imported);
	}
}

async function loadConsumerConfig(): Promise<DashboardConfig> {
	for (const fileName of CONFIG_CANDIDATES) {
		const configPath = path.resolve(process.cwd(), fileName);
		if (!fs.existsSync(configPath)) {
			continue;
		}

		if (configPath.endsWith('.ts')) {
			console.warn(
				`\nWarning: ${fileName} is not directly executable at runtime. Use .js/.cjs/.mjs instead.`,
			);
			continue;
		}

		try {
			const cfg = await loadConfigFile(configPath);
			console.log(`\nFound ${fileName} — applying your settings.`);
			return cfg;
		} catch (err) {
			console.warn(
				`\nWarning: could not read ${fileName} — trying next fallback.\n${String(err)}`,
			);
		}
	}

	return {};
}

function injectConfig(html: string, cfg: Required<DashboardConfig>): string {
	const configBlock = `const CONFIG = {
  pageTitle:        ${JSON.stringify(cfg.pageTitle)},
  projectName:      ${JSON.stringify(cfg.projectName)},
  brandName:        ${JSON.stringify(cfg.brandName)},
  historyIndexPath: ${JSON.stringify(cfg.historyIndexPath)},
  emptyTitle:       ${JSON.stringify(cfg.emptyTitle)},
  emptyMessage:     ${JSON.stringify(cfg.emptyMessage)},
  errorTitle:       ${JSON.stringify(cfg.errorTitle)},
  errorMessage:     ${JSON.stringify(cfg.errorMessage)},
};`;

	// Replace the entire CONFIG block between the banner comments
	const configBlockPattern =
		/\/\/ ─+\r?\n\/\/ CONFIG[^\r\n]*\r?\n\/\/ ─+\r?\nconst CONFIG = \{[\s\S]*?\};\r?\n\/\/ ─+/;
	if (!configBlockPattern.test(html)) {
		throw new Error(
			'Could not find the CONFIG block in dashboard/index.html. Dashboard template format may have changed.',
		);
	}

	return html.replace(
		configBlockPattern,
		`// ─────────────────────────────────────────────────────────────────────────────\n// CONFIG — generated by pw-history-init · edit pw-dashboard.config.js to change\n// ─────────────────────────────────────────────────────────────────────────────\n${configBlock}\n// ─────────────────────────────────────────────────────────────────────────────`,
	);
}

async function main() {
	const consumerCfg = await loadConsumerConfig();
	const cfg: Required<DashboardConfig> = { ...DEFAULTS, ...consumerCfg };

	const src = path.resolve(__dirname, '../../dashboard/index.html');
	const destDir = path.resolve(process.cwd(), cfg.historyDir);
	const dest = path.join(destDir, 'index.html');

	if (!fs.existsSync(destDir)) {
		fs.mkdirSync(destDir, { recursive: true });
	}

	const template = fs.readFileSync(src, 'utf-8');
	const output = injectConfig(template, cfg);

	fs.writeFileSync(dest, output, 'utf-8');

	console.log(`\n✓ Dashboard written to:\n  ${dest}\n`);
	if (!consumerCfg.projectName) {
		console.log(
			`Tip: create pw-dashboard.config.js or pw-dashboard.config.cjs in your project root to set your project name:\n`,
		);
		console.log(`  module.exports = {`);
		console.log(`    projectName: 'Your Project Name',`);
		console.log(`  };\n`);
	}
	console.log(`Serve with: npx serve ${cfg.historyDir}\n`);
}

main().catch((err: unknown) => {
	console.error(`\nError: failed to initialize dashboard.\n${String(err)}\n`);
	process.exitCode = 1;
});
