name: Dependabot Changeset Helper
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # 1st day of month 00:00 UTC

jobs:
  add-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.CHANGESETS_TOKEN }}

      - name: Create Dummy Changeset
        run: |
          mkdir -p .changeset
          CHANGESET_ID=${{ github.run_id }}
          CHANGES=$(node - <<'NODE'
          const { readdirSync, statSync, readFileSync } = require('fs');
          const { join } = require('path');
          const pkgs = readdirSync('packages').filter((p) => statSync(join('packages', p)).isDirectory());
          const names = pkgs
            .map((pkg) => {
              const pkgJson = JSON.parse(readFileSync(join('packages', pkg, 'package.json'), 'utf8'));
              return pkgJson.name;
            })
            .filter(Boolean);
          if (!names.length) {
            process.exit(1);
          }
          console.log(names.map((name) => `"${name}": patch`).join('\n'));
          NODE
          )

          printf -- "---\n%s\n---\nchore(deps): automated dependency update\n" "$CHANGES" > .changeset/dependabot-${CHANGESET_ID}.md

      - name: Commit Changeset
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .changeset/*.md
          git commit -m "chore: add changeset for dependabot update"
          git push